name: Frontend Deployment

on:
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio principal
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Configurar credenciales AWS para S3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # 3. Sincronizar el build con el bucket S3
      - name: Deploy to S3
        uses: aws-actions/s3-sync@v2
        with:
          source-dir: ./ReactDevops2024/build  # Carpeta de salida del build de React
          destination-bucket: frontendbucket303898
          bucket-region: us-east-1
          delete: true  # Elimina archivos que ya no están en el build local

      # 4. Configurar el bucket como sitio web estático
      - name: Enable Static Website Hosting
        run: |
          aws s3 website s3://frontendbucket303898/ --index-document index.html --error-document index.html
