name: Deploy Frontend to S3

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1  

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://frontendbucket303898/ --delete
          aws s3 website s3://frontendbucket303898/ --index-document index.html --error-document index.html

      - name: Set public read access
        run: |
          aws s3api put-bucket-policy --bucket frontendbucket303898 --policy '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::frontendbucket303898/*"
              }
            ]
          }'
