name: CI/CD Frontend Deployment

on:
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio principal
      - name: Checkout Main Repository
        uses: actions/checkout@v3

      # 2. Construcción del aplicativo React usando NX
      - name: Build Catalog Application
        run: |
          # Instalar Node.js si no está disponible
          echo "Setting up Node.js"
          node -v || curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs

          # Instalar dependencias
          echo "Installing dependencies"
          npm install

          # Construir el proyecto 'catalog' con NX
          echo "Building project catalog"
          npx nx build catalog

      - name: Build Checkout Application
        run: |
          # Construir el proyecto 'checkout' con NX
          echo "Building project checkout"
          npx nx build checkout

      # 3. Verificar el contenido del directorio de salida para ambos proyectos
      - name: Verify Build Output
        run: |
          echo "Checking build output directory..."
          ls -al ./dist/apps/catalog
          ls -al ./dist/apps/checkout

      # 4. Configurar credenciales AWS para S3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # 5. Sincronizar los archivos construidos con el bucket S3
      - name: Deploy Catalog to S3
        run: |
          aws s3 sync ./dist/apps/catalog s3://frontendbucket303898 --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy Checkout to S3
        run: |
          aws s3 sync ./dist/apps/checkout s3://frontendbucket303898 --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      # 6. Configurar el bucket como un sitio web estático (opcional)
      - name: Enable Static Website Hosting
        run: |
          aws s3 website s3://frontendbucket303898/ --index-document index.html --error-document index.html
