name: Deploy Services to EKS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequear el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Autenticarse con EKS
      - name: Authenticate with EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name devops-cluster

      # 4. Desplegar cada servicio
      - name: Deploy to EKS
        run: |
          for SERVICE in orders-service payments-service products-service shipping-service; do
            kubectl apply -f k8s/$SERVICE-deployment.yaml
          done
